version: '3.7'

services:
  db:
    image: postgres:9.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gcsb.connect.training.network

  gcsb.connect.training.webapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
      ALLOWED_HOSTS: localhost
      TRAEFIK_PATH: ""
      DBCONN: "Server=db;Port=5432;Database=postgres;User Id=postgres;Password=postgres;"
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - gcsb.connect.training.network

networks:
  gcsb.connect.training.network:

volumes:
  pgdata: